spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=employee-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://employee-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.server.webflux.routes[1].id=project-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://project-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/projects/**

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable discovery locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Explicitly declare as reactive
spring.main.web-application-type=reactive
