<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>springboot-microservices</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <name>Spring Boot Microservices Parent</name>

  <modules>
    <module>eureka-server</module>
    <module>api-gateway</module>
    <module>employee-service</module>
    <module>project-service</module>
  </modules>

  <properties>
    <java.version>17</java.version>
    <spring-cloud.version>2022.0.4</spring-cloud.version>
      <sonar.organization>vinay-2403-1</sonar.organization>
      <sonar.host.url>https://sonarcloud.io</sonar.host.url>
      <sonar.coverage.exclusions>
        **/api-gateway/**,
        **/eureka-server/**,
        **/ModelMapperConfig.java
      </sonar.coverage.exclusions>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.11.0</version>
          <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
